function f = QuadrotorStateFcn(in1,in2)
%QuadrotorStateFcn
%    F = QuadrotorStateFcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    31-Oct-2023 22:41:39

p_t = in1(10,:);
phi_t = in1(7,:);
psy_t = in1(9,:);
q_t = in1(11,:);
r_t = in1(12,:);
theta_t = in1(8,:);
w1 = in2(1,:);
w2 = in2(2,:);
w3 = in2(3,:);
w4 = in2(4,:);
x_dot_t = in1(4,:);
y_dot_t = in1(5,:);
z_dot_t = in1(6,:);
t2 = cos(phi_t);
t3 = cos(psy_t);
t4 = cos(theta_t);
t5 = sin(phi_t);
t6 = sin(psy_t);
t7 = sin(theta_t);
t8 = tan(theta_t);
t9 = w1.^2;
t10 = w2.^2;
t11 = w3.^2;
t12 = w4.^2;
t13 = 1.0./t4;
t14 = t9+t10+t11+t12;
t15 = t9.*2.631338092623101e+1;
t16 = t10.*2.631338092623101e+1;
t17 = t11.*2.631338092623101e+1;
t18 = t12.*2.631338092623101e+1;
t19 = -t15;
mt1 = [x_dot_t;y_dot_t;z_dot_t;t14.*(t5.*t6+t2.*t3.*t7).*(2.0e+1./1.3e+1)-x_dot_t.^2./6.5e+1;t14.*(t3.*t5-t2.*t6.*t7).*(-2.0e+1./1.3e+1)-y_dot_t.^2./6.5e+1;z_dot_t.^2.*(-9.0./1.3e+2)+t2.*t4.*t14.*(2.0e+1./1.3e+1)-9.81e+2./1.0e+2;p_t+q_t.*t5.*t8+r_t.*t2.*t8;q_t.*t2-r_t.*t5;q_t.*t5.*t13+r_t.*t2.*t13;p_t.*(-1.144060040270913e+1)-t16+t17+t18+t19-q_t.*r_t.*9.813747025443894e-1];
mt2 = [q_t.*(-1.144060040270913e+1)+t16+t17-t18+t19+p_t.*r_t.*9.813747025443894e-1];
mt3 = [r_t.*(-5.774072106612468)+t9.*4.330554079959351e-5-t10.*4.330554079959351e-5+t11.*4.330554079959351e-5-t12.*4.330554079959351e-5];
f = [mt1;mt2;mt3];
end
