function f = QuadrotorStateFcn(in1,in2)
%QuadrotorStateFcn
%    F = QuadrotorStateFcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Oct-2023 20:29:45

p_t = in1(10,:);
phi_t = in1(7,:);
psy_t = in1(9,:);
q_t = in1(11,:);
r_t = in1(12,:);
theta_t = in1(8,:);
w1 = in2(1,:);
w2 = in2(2,:);
w3 = in2(3,:);
w4 = in2(4,:);
x_dot_t = in1(4,:);
y_dot_t = in1(5,:);
z_dot_t = in1(6,:);
t2 = cos(phi_t);
t3 = cos(psy_t);
t4 = cos(theta_t);
t5 = sin(phi_t);
t6 = sin(theta_t);
t7 = tan(theta_t);
t8 = w1.^2;
t9 = w2.^2;
t10 = w3.^2;
t11 = w4.^2;
t13 = w1+w2+w3+w4;
t12 = 1.0./t4;
t14 = t8+t9+t10+t11;
t15 = t8.*8.236088229910304e-4;
t16 = t9.*8.236088229910304e-4;
t17 = t10.*8.236088229910304e-4;
t18 = t11.*8.236088229910304e-4;
t19 = -t15;
mt1 = [x_dot_t;y_dot_t;z_dot_t;t14.*(t5.*sin(psy_t)+t2.*t3.*t6).*4.815384615384615e-5-x_dot_t.^2./6.5e+1;t14.*(t3.*t5-t3.*t5.*t6).*(-4.815384615384615e-5)-y_dot_t.^2./6.5e+1;z_dot_t.^2.*(-9.0./1.3e+2)+t2.*t4.*t14.*4.815384615384615e-5-9.81e+2./1.0e+2];
mt2 = [p_t+q_t.*t5.*t7+r_t.*t2.*t7;q_t.*t2-r_t.*t5;q_t.*t5.*t12+r_t.*t2.*t12;p_t.*(-1.144060040270913e+1)-t16+t17+t18+t19-q_t.*r_t.*9.813747025443894e-1-q_t.*t13.*1.144060040270913e+2];
mt3 = [q_t.*(-1.144060040270913e+1)+t16+t17-t18+t19+p_t.*r_t.*9.813747025443894e-1+p_t.*t13.*1.144060040270913e+2];
mt4 = [r_t.*(-5.774072106612468)+t8.*4.330554079959351e-5-t9.*4.330554079959351e-5+t10.*4.330554079959351e-5-t11.*4.330554079959351e-5];
f = [mt1;mt2;mt3;mt4];
end
